language: cpp
# gcc is clang on mac
compiler: gcc

matrix:
  fast_finish: true
  include:
  - name: Ubuntu qmake Qt5.5.1
    os: linux
    dist: trusty
    group: stable
    before_install:
      - sudo apt-get -y install libqt5x11extras5-dev
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt551-trusty'
        update: true
        packages:
        - qt55base
        - qt55tools
        - qt55x11extras
        - libqt5x11extras5-dev
        - gcc-9
        - g++-9
    script:
        - PATH="/opt/qt55/bin:$PATH"
        - CXX="g++-9"
        - CC="gcc-9"
        - qt55-env.sh
        - qmake
        - make
        - make install
  - name: Ubuntu qmake dll
    os: linux
    dist: bionic
    group: stable
    services:
        - xvfb
    compiler: gcc
    before_install:
      - sudo apt-get -y install libqt5x11extras5-dev
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
        update: true
        packages:
        - qt514base
        - qt514tools
        - qt514x11extras
        - libqt5x11extras5-dev
        - gcc-9
        - g++-9
        - libc6-i386
        - libgl-dev
        - libgl1-mesa-dev
        - mesa-common-dev
    script:
        - PATH="/opt/qt514/bin:$PATH"
        - CXX="g++-9"
        - CC="gcc-9"
        - qt514-env.sh
        - qmake
        - make
        - make install
  - name: Ubuntu qmake static
    os: linux
    dist: bionic
    group: stable
    services:
        - xvfb
    compiler: gcc
    before_install:
      - sudo apt-get -y install libqt5x11extras5-dev  
    addons:  
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
        update: true
        packages:
        - qt514base
        - qt514tools
        - qt514x11extras
        - libqt5x11extras5-dev
        - gcc-9
        - g++-9
        - libc6-i386
        - libgl-dev
        - libgl1-mesa-dev
        - mesa-common-dev
    script:
        - PATH="/opt/qt514/bin:$PATH"
        - CXX="g++-9"
        - CC="gcc-9"
        - qt514-env.sh
        - qmake "CONFIG+=adsBuildStatic"
        - make
        - make install
  - name: Ubuntu CMake dll
    os: linux
    dist: bionic
    group: stable
    services:
        - xvfb
    compiler: gcc
    before_install:
      - sudo apt-get -y install libqt5x11extras5-dev
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
        update: true
        packages:
        - qt514base
        - qt514tools
        - qt514x11extras
        - libqt5x11extras5-dev
        - gcc-9
        - g++-9
        - libc6-i386
        - libgl-dev
        - libgl1-mesa-dev
        - mesa-common-dev
    script:
        - PATH="/opt/qt514/bin:$PATH"
        - CXX="g++-9"
        - CC="gcc-9"
        - qt514-env.sh
        - mkdir ./build
        - cd ./build
        - cmake --version
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_STATIC=OFF -DBUILD_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STATIC=OFF -DBUILD_EXAMPLES=ON -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
  - name: Ubuntu CMake Static
    os: linux
    dist: bionic
    group: stable
    services:
        - xvfb
    compiler: gcc
    before_install:
      - sudo apt-get -y install libqt5x11extras5-dev
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
        update: true
        packages:
        - qt514base
        - qt514tools
        - qt514x11extras
        - libqt5x11extras5-dev
        - gcc-9
        - g++-9
        - libc6-i386
        - libgl-dev
        - libgl1-mesa-dev
        - mesa-common-dev
    script:
        - PATH="/opt/qt514/bin:$PATH"
        - CXX="g++-9"
        - CC="gcc-9"
        - qt514-env.sh
        - mkdir ./build
        - cd ./build
        - cmake --version
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_STATIC=ON -DBUILD_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
        - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STATIC=ON -DBUILD_EXAMPLES=ON -DCMAKE_DEBUG_POSTFIX=d -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
  - name: macOS CMake dll
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
        - qt
        update: true
    script:
        - PATH="/usr/local/opt/qt5/bin:$PATH"
        - mkdir -p build
        - cd build
        - cmake --version
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_DEBUG_POSTFIX=_debug -DBUILD_EXAMPLES=ON -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_EXAMPLES=ON -DBUILD_STATIC=OFF -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
  - name: macOS CMake static
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
        - qt
        update: true
    script:
        - PATH="/usr/local/opt/qt5/bin:$PATH"
        - mkdir -p build
        - cd build
        - cmake --version
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=DEBUG -DCMAKE_DEBUG_POSTFIX=_debug -DBUILD_EXAMPLES=ON -DBUILD_STATIC=ON -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_EXAMPLES=ON -DBUILD_STATIC=ON -DCMAKE_INSTALL_PREFIX="./installed" ../
        - cmake --build .
        - cmake --build . --target install
  - name: macOS qmake dll
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
        - qt
        update: true
    script:
        - PATH="/usr/local/opt/qt5/bin:$PATH"
        - qmake
        - make
        - make install
  - name: macOS qmake static
    os: osx
    osx_image: xcode11.3
    compiler: clang
    addons:
      homebrew:
        packages:
        - qt
        update: true
    script:
        - PATH="/usr/local/opt/qt5/bin:$PATH"
        - qmake "CONFIG+=adsBuildStatic"
        - make
        - make install
notifications:
  email: false

