name: Update translation files

on: 
  workflow_dispatch:  
  schedule:           
    - cron: '35 1 * * 0'  

jobs:
  lupdate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5'

      - name: Run lupdate
        run: lupdate src/NotepadNext.pro

      - name: Commit translation changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update translation files
          file_pattern: 'i18n/*.ts'
